### ISSUE TITLE
Errors trying to upload a modified zip as import

### ISSUE THREAD

**Issue by Koleok** [jsreport/jsreport-import-export#1]
When creating my own import package, zipping on osx, and attempting to import the result I am getting the following error:
![image](https://cloud.githubusercontent.com/assets/10928312/26427335/483126d2-40aa-11e7-89cb-1ee362fbe198.png)

the trace in text:
```bash
Error occured - Cannot read property 'entityType' of undefined
Stak - TypeError: Cannot read property 'entityType' of undefined
    at Object.module.exports.base64ToBuffer (/usr/src/app/node_modules/jsreport-import-export/lib/helpers.js:3:47)
    at /usr/src/app/node_modules/jsreport-import-export/lib/exports.js:97:15
    at tryCatcher (/usr/src/app/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/usr/src/app/node_modules/bluebird/js/release/reduce.js:155:18)
    at Object.gotAccum (/usr/src/app/node_modules/bluebird/js/release/reduce.js:144:25)
    at Object.tryCatcher (/usr/src/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/src/app/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/src/app/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/usr/src/app/node_modules/bluebird/js/release/promise.js:606:10)
    at Async._drainQueue (/usr/src/... Error: Error occured - Cannot read property 'entityType' of undefined
Stak - TypeError: Cannot read property 'entityType' of undefined
    at Object.module.exports.base64ToBuffer (/usr/src/app/node_modules/jsreport-import-export/lib/helpers.js:3:47)
    at /usr/src/app/node_modules/jsreport-import-export/lib/exports.js:97:15
    at tryCatcher (/usr/src/app/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/usr/src/app/node_modules/bluebird/js/release/reduce.js:155:18)
    at Object.gotAccum (/usr/src/app/node_modules/bluebird/js/release/reduce.js:144:25)
    at Object.tryCatcher (/usr/src/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/src/app/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/src/app/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/usr/src/app/node_modules/bluebird/js/release/promise.js:606:10)
    at Async._drainQueue (/usr/src/...
    at v (https://flex.jsreportonline.net/studio/assets/client.js?ec9ae6087d926c6046d2:3:26581)
    at https://flex.jsreportonline.net/studio/assets/client.js?ec9ae6087d926c6046d2:3:27234
    at f.callback (https://flex.jsreportonline.net/studio/assets/client.js?ec9ae6087d926c6046d2:40:11564)
    at f.<anonymous> (https://flex.jsreportonline.net/studio/assets/client.js?ec9ae6087d926c6046d2:40:7901)
    at f.n.emit (https://flex.jsreportonline.net/studio/assets/client.js?ec9ae6087d926c6046d2:3:29267)
    at XMLHttpRequest.n.onreadystatechange (https://flex.jsreportonline.net/studio/assets/client.js?ec9ae6087d926c6046d2:40:12419)
```

Is there any special way to create the zip?

**Comment by pofider** [comment]
How do you create your import package?
Did you try to export and observe the supported format before?

**Comment by Koleok** [comment]
@pofider Yep I am just editing the `content` and `helpers` keys in the `template` files, then re-zipping _(with ['archiver`](https://www.npmjs.com/package/archiver))_ and attempting to upload the result.

**Comment by Koleok** [comment]
Actually if i export from jsreportonline.net, then unzip/rezip that export, i get the same error when trying to import it, which leads me to believe the issue has to do with with creating the zip file and not with its contents

**Comment by Koleok** [comment]
This was my reason for using [`archiver`](https://www.npmjs.com/package/archiver) since i saw that you [did the same](https://github.com/jsreport/jsreport-import-export/blob/master/lib/exports.js#L145) but zipping with osx, `zip` on the command line, and [`archiver`](https://www.npmjs.com/package/archiver) have all given me the same error

**Comment by pofider** [comment]
ok. I was trying to export from jsreportonline, decompress in windows total commander, edit the template content, compress back, import to jsreportonline. Everything seems to be fine for me.

@bjrmatos Maybe you can later try this on the osx? Thank you

**Comment by bjrmatos** [comment]
i've tried the following methods after exporting a backup from my jsreportonline account

### changing one template content in backup and re-zip using OSX "Compress" context menu option

<img width="339" alt="captura de pantalla 2017-05-25 a las 1 14 29 p m" src="https://cloud.githubusercontent.com/assets/4262050/26464078/1ca9786e-414c-11e7-9d6f-02c14956a52a.png">

result:

<details>
Error occured - Unexpected token �
Stak - SyntaxError: Unexpected token �
    at Object.parse (native)
    at /Volumes/DATA/workspace/jsreport-quick-test/node_modules/jsreport-import-export/lib/exports.js:51:38
    at /Volumes/DATA/workspace/jsreport-quick-test/node_modules/stream-to-array/index.js:54:9
    at nextTickCallbackWith0Args (node.js:489:9)
    at process._tickCallback (node.js:418:13)... Error: Error occured - Unexpected token �
Stak - SyntaxError: Unexpected token �
    at Object.parse (native)
    at /Volumes/DATA/workspace/jsreport-quick-test/node_modules/jsreport-import-export/lib/exports.js:51:38
    at /Volumes/DATA/workspace/jsreport-quick-test/node_modules/stream-to-array/index.js:54:9
    at nextTickCallbackWith0Args (node.js:489:9)
    at process._tickCallback (node.js:418:13)...
    at v (http://localhost:5488/studio/assets/client.js?519e791128e7950408d4:3:26581)
    at http://localhost:5488/studio/assets/client.js?519e791128e7950408d4:3:27234
    at f.callback (http://localhost:5488/studio/assets/client.js?519e791128e7950408d4:40:11564)
    at f.<anonymous> (http://localhost:5488/studio/assets/client.js?519e791128e7950408d4:40:7901)
    at f.n.emit (http://localhost:5488/studio/assets/client.js?519e791128e7950408d4:3:29267)
    at XMLHttpRequest.n.onreadystatechange (http://localhost:5488/studio/assets/client.js?519e791128e7950408d4:40:12419)
</details>

### changing one template content in backup and re-zip using `zip -r export-modified-zipped-with-zip-command.zip templates` command in OSX

result:

<details>
Error occured - Unexpected token �
Stak - SyntaxError: Unexpected token �
    at Object.parse (native)
    at /Volumes/DATA/workspace/jsreport-quick-test/node_modules/jsreport-import-export/lib/exports.js:51:38
    at /Volumes/DATA/workspace/jsreport-quick-test/node_modules/stream-to-array/index.js:54:9
    at nextTickCallbackWith0Args (node.js:489:9)
    at process._tickCallback (node.js:418:13)... Error: Error occured - Unexpected token �
Stak - SyntaxError: Unexpected token �
    at Object.parse (native)
    at /Volumes/DATA/workspace/jsreport-quick-test/node_modules/jsreport-import-export/lib/exports.js:51:38
    at /Volumes/DATA/workspace/jsreport-quick-test/node_modules/stream-to-array/index.js:54:9
    at nextTickCallbackWith0Args (node.js:489:9)
    at process._tickCallback (node.js:418:13)...
    at v (http://localhost:5488/studio/assets/client.js?519e791128e7950408d4:3:26581)
    at http://localhost:5488/studio/assets/client.js?519e791128e7950408d4:3:27234
    at f.callback (http://localhost:5488/studio/assets/client.js?519e791128e7950408d4:40:11564)
    at f.<anonymous> (http://localhost:5488/studio/assets/client.js?519e791128e7950408d4:40:7901)
    at f.n.emit (http://localhost:5488/studio/assets/client.js?519e791128e7950408d4:3:29267)
    at XMLHttpRequest.n.onreadystatechange (http://localhost:5488/studio/assets/client.js?519e791128e7950408d4:40:12419)
</details>

### changing one template content in backup and re-zip using `zip -r -9 export-modified-zipped-with-zip-command-and-9-option.zip templates` command in OSX

result:

**everything works normally**

<img width="928" alt="captura de pantalla 2017-05-25 a las 1 25 08 p m" src="https://cloud.githubusercontent.com/assets/4262050/26464502/9da4b0e0-414d-11e7-987a-d756665b0c0b.png">



@Koleok so i think that you can safely re-zip the export using `zip -r -9 ...` 

@pofider we can take a look at why the importing validation fails after re-zip with other zip methods but it seems like an encoding issue or anything else and i'm not sure if it worth to give a look

**Comment by Koleok** [comment]
@bjrmatos Awesome thanks for this, i'll give it a try right now

**Comment by Koleok** [comment]
🤔  welp i am still having the same error when re-zipping the freshly exported/unzipped package with `zip -r -9 ...`

<details>
  <pre>
    Error occured - Cannot read property 'entityType' of undefined
Stak - TypeError: Cannot read property 'entityType' of undefined
    at Object.module.exports.base64ToBuffer (/usr/src/app/node_modules/jsreport-import-export/lib/helpers.js:3:47)
    at /usr/src/app/node_modules/jsreport-import-export/lib/exports.js:97:15
    at tryCatcher (/usr/src/app/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/usr/src/app/node_modules/bluebird/js/release/reduce.js:155:18)
    at Object.gotAccum (/usr/src/app/node_modules/bluebird/js/release/reduce.js:144:25)
    at Object.tryCatcher (/usr/src/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/src/app/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/src/app/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/usr/src/app/node_modules/bluebird/js/release/promise.js:606:10)
    at Async._drainQueue (/usr/src/... Error: Error occured - Cannot read property 'entityType' of undefined
Stak - TypeError: Cannot read property 'entityType' of undefined
    at Object.module.exports.base64ToBuffer (/usr/src/app/node_modules/jsreport-import-export/lib/helpers.js:3:47)
    at /usr/src/app/node_modules/jsreport-import-export/lib/exports.js:97:15
    at tryCatcher (/usr/src/app/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/usr/src/app/node_modules/bluebird/js/release/reduce.js:155:18)
    at Object.gotAccum (/usr/src/app/node_modules/bluebird/js/release/reduce.js:144:25)
    at Object.tryCatcher (/usr/src/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/src/app/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/src/app/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/usr/src/app/node_modules/bluebird/js/release/promise.js:606:10)
    at Async._drainQueue (/usr/src/...
    at v (https://flex.jsreportonline.net/studio/assets/client.js?ec9ae6087d926c6046d2:3:26581)
    at https://flex.jsreportonline.net/studio/assets/client.js?ec9ae6087d926c6046d2:3:27234
    at f.callback (https://flex.jsreportonline.net/studio/assets/client.js?ec9ae6087d926c6046d2:40:11564)
    at f.<anonymous> (https://flex.jsreportonline.net/studio/assets/client.js?ec9ae6087d926c6046d2:40:7901)
    at f.n.emit (https://flex.jsreportonline.net/studio/assets/client.js?ec9ae6087d926c6046d2:3:29267)
    at XMLHttpRequest.n.onreadystatechange (https://flex.jsreportonline.net/studio/assets/client.js?ec9ae6087d926c6046d2:40:12419)
  </pre>
</details>

**Comment by bjrmatos** [comment]
@Koleok are you using a backup with multiple items? try exporting just one template.. since i can't reproduce the error my best advice would be that you try to debug the application using something like `node-inspector` and putting a breakpoint [here](https://github.com/jsreport/jsreport-import-export/blob/master/lib/exports.js#L93) and continue the flow and inspect where it fails exactly.

**Comment by Koleok** [comment]
@bjrmatos Will do, i'd love to get this working so I will keep hunting for a solution.

I'd was actually thinking of publishing an OSS `contrib` module once i am done with this, basically it lets you keep a normal repo with your source and template files version controlled, then just run a build job and generate the zip artifact for import on jsreportonline.net

If you guys already have a solution for that problem, well i be glad to dump what i am doing haha :)

**Comment by bjrmatos** [comment]
@Koleok of course we have the interest, there is always a place for OSS contributions, the idea of what you are working on sounds great and we don't have similar solution yet, so it will be definitely great to see what you prepare.

how was the debugging? did you found something meaningful? another thing you can try is to put some `console.log` before this [line], that folder should be present in your `node_modules` folder, try to log the following: `console.log(collection); console.log(model.entitySets)` and post here your results.

**Comment by pofider** [comment]
Closing this one because of inactivity. Feel free to reopen if there is something for us to comment or fix.
